[package]
name = "libaiml"
version = "0.1.0"
authors = ["hojjat"]
edition = "2018"



[lib]
name = "libaiml"
path = "src/lib.rs"


[dependencies]
glob = "0.3.0"
log = "0.4"
env_logger = "0.8.2"
minidom = "0.12.0"
indextree = "4"



